mklink default_patch.tre E:\Tarkin\default_patch.tre 
mklink patch_sku1_14_00.tre E:\Tarkin\patch_sku1_14_00.tre 
mklink patch_14_00.tre E:\Tarkin\patch_14_00.tre 
mklink patch_sku1_13_00.tre E:\Tarkin\patch_sku1_13_00.tre 
mklink patch_13_00.tre E:\Tarkin\patch_13_00.tre 
mklink patch_sku1_12_00.tre E:\Tarkin\patch_sku1_12_00.tre 
mklink patch_12_00.tre E:\Tarkin\patch_12_00.tre 
mklink patch_11_03.tre E:\Tarkin\patch_11_03.tre 
mklink data_sku1_07.tre E:\Tarkin\data_sku1_07.tre 
mklink patch_11_02.tre E:\Tarkin\patch_11_02.tre 
mklink data_sku1_06.tre E:\Tarkin\data_sku1_06.tre 
mklink patch_11_01.tre E:\Tarkin\patch_11_01.tre 
mklink patch_11_00.tre E:\Tarkin\patch_11_00.tre 
mklink data_sku1_05.tre E:\Tarkin\data_sku1_05.tre 
mklink data_sku1_04.tre E:\Tarkin\data_sku1_04.tre 
mklink data_sku1_03.tre E:\Tarkin\data_sku1_03.tre 
mklink data_sku1_02.tre E:\Tarkin\data_sku1_02.tre 
mklink data_sku1_01.tre E:\Tarkin\data_sku1_01.tre 
mklink data_sku1_00.tre E:\Tarkin\data_sku1_00.tre 
mklink patch_10.tre E:\Tarkin\patch_10.tre 
mklink patch_09.tre E:\Tarkin\patch_09.tre 
mklink patch_08.tre E:\Tarkin\patch_08.tre 
mklink patch_07.tre E:\Tarkin\patch_07.tre 
mklink patch_06.tre E:\Tarkin\patch_06.tre 
mklink patch_05.tre E:\Tarkin\patch_05.tre 
mklink patch_04.tre E:\Tarkin\patch_04.tre 
mklink patch_03.tre E:\Tarkin\patch_03.tre 
mklink patch_02.tre E:\Tarkin\patch_02.tre 
mklink patch_01.tre E:\Tarkin\patch_01.tre 
mklink patch_00.tre E:\Tarkin\patch_00.tre 
mklink data_other_00.tre E:\Tarkin\data_other_00.tre 
mklink data_static_mesh_01.tre E:\Tarkin\data_static_mesh_01.tre 
mklink data_static_mesh_00.tre E:\Tarkin\data_static_mesh_00.tre 
mklink data_texture_07.tre E:\Tarkin\data_texture_07.tre 
mklink data_texture_06.tre E:\Tarkin\data_texture_06.tre 
mklink data_texture_05.tre E:\Tarkin\data_texture_05.tre 
mklink data_texture_04.tre E:\Tarkin\data_texture_04.tre 
mklink data_texture_03.tre E:\Tarkin\data_texture_03.tre 
mklink data_texture_02.tre E:\Tarkin\data_texture_02.tre 
mklink data_texture_01.tre E:\Tarkin\data_texture_01.tre 
mklink data_texture_00.tre E:\Tarkin\data_texture_00.tre 
mklink data_skeletal_mesh_01.tre E:\Tarkin\data_skeletal_mesh_01.tre 
mklink data_skeletal_mesh_00.tre E:\Tarkin\data_skeletal_mesh_00.tre 
mklink data_animation_00.tre E:\Tarkin\data_animation_00.tre 
mklink data_sample_04.tre E:\Tarkin\data_sample_04.tre 
mklink data_sample_03.tre E:\Tarkin\data_sample_03.tre 
mklink data_sample_02.tre E:\Tarkin\data_sample_02.tre 
mklink data_sample_01.tre E:\Tarkin\data_sample_01.tre 
mklink data_sample_00.tre E:\Tarkin\data_sample_00.tre 
mklink data_music_00.tre E:\Tarkin\data_music_00.tre 
mklink bottom.tre E:\Tarkin\bottom.tre 